export const SETTING_KEYS = {
  DEFAULT_PURCHASE_VAT_RATE: 'DEFAULT_PURCHASE_VAT_RATE',
  THREE_WAY_MATCHING_QTY_TOLERANCE: 'THREE_WAY_MATCHING_QTY_TOLERANCE',
  THREE_WAY_MATCHING_PRICE_TOLERANCE_PERCENT:
    'THREE_WAY_MATCHING_PRICE_TOLERANCE_PERCENT',
} as const;
