import { Injectable, BadRequestException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { ExportDocument, DocumentType } from './entities/export-document.entity';
import { InjectQueue } from '@nestjs/bullmq';
import { Queue } from 'bullmq';
const PdfPrinter = require('pdfmake');
import * as fs from 'fs';
import * as path from 'path';

@Injectable()
export class ExportDocumentsService {
  constructor(
    @InjectRepository(ExportDocument)
    private docsRepository: Repository<ExportDocument>,
    @InjectQueue('document-generation')
    private readonly docQueue: Queue
  ) {}

  /**
   * Render PDF synchronously for immediate download
   */
  async generateDocumentPdf(shipmentId: string, type: 'CI' | 'PL'): Promise<Buffer> {
    const docType = type === 'CI' ? DocumentType.COMMERCIAL_INVOICE : DocumentType.PACKING_LIST;
    
    // Find the latest generated document for this shipment
    const doc = await this.docsRepository.findOne({
      where: { shipmentId, documentType: docType },
      order: { createdAt: 'DESC' }
    });

    if (!doc) {
      throw new BadRequestException(`Chưa có dữ liệu snapshot cho chứng từ ${type} của lô hàng này. Vui lòng yêu cầu tạo snapshot trước.`);
    }

    // Reuse the definition logic
    const docDefinition = type === 'CI' 
      ? this.getCommercialInvoiceDefinition(doc)
      : this.getPackingListDefinition(doc);

    const fonts = {
      Helvetica: {
        normal: 'Helvetica',
        bold: 'Helvetica-Bold',
        italics: 'Helvetica-Oblique',
        bolditalics: 'Helvetica-BoldOblique'
      }
    };

    const printer = new PdfPrinter(fonts);
    const pdfDoc = printer.createPdfKitDocument(docDefinition);
    
    return new Promise((resolve, reject) => {
      const chunks: any[] = [];
      pdfDoc.on('data', (chunk) => chunks.push(chunk));
      pdfDoc.on('end', () => resolve(Buffer.concat(chunks)));
      pdfDoc.on('error', (err) => reject(err));
      pdfDoc.end();
    });
  }

  /**
   * Đẩy yêu cầu Render PDF vào Background Queue
   */
  async requestDocumentGeneration(shipmentId: string, type: DocumentType, snapshotData: any) {
    const doc = this.docsRepository.create({
      shipmentId,
      documentType: type,
      snapshotData,
      isGenerated: false,
      fileName: `${type}_${shipmentId}_${Date.now()}.pdf`,
      fileUrl: ''
    });
    
    const savedDoc = await this.docsRepository.save(doc);

    // Push to BullMQ for background processing
    await this.docQueue.add('generate-pdf', { documentId: savedDoc.id });

    return {
      message: 'Yêu cầu xuất PDF đã được đưa vào hàng đợi xử lý ngầm.',
      documentId: savedDoc.id
    };
  }

  /**
   * Logic render PDF thực tế (Dùng trong Worker)
   */
  async generatePdf(documentId: string) {
    const doc = await this.docsRepository.findOne({ where: { id: documentId } });
    if (!doc) return;

    // Định nghĩa nội dung PDF dựa trên DocumentType
    let docDefinition: any;

    if (doc.documentType === DocumentType.COMMERCIAL_INVOICE) {
      docDefinition = this.getCommercialInvoiceDefinition(doc);
    } else if (doc.documentType === DocumentType.PACKING_LIST) {
      docDefinition = this.getPackingListDefinition(doc);
    } else {
      // Fallback cho các loại khác
      docDefinition = {
        content: [
          { text: doc.documentType, style: 'header' },
          { text: `Shipment ID: ${doc.shipmentId}`, margin: [0, 10] },
          { text: 'Snapshot Data:', style: 'subheader' },
          { text: JSON.stringify(doc.snapshotData, null, 2), font: 'Courier' },
          { text: '\n\nGenerated by Mini ERP Export System', style: 'footer' }
        ],
        styles: {
          header: { fontSize: 22, bold: true },
          subheader: { fontSize: 16, bold: true, margin: [0, 10, 0, 5] },
          footer: { fontSize: 10, italic: true, alignment: 'center' }
        },
        defaultStyle: { font: 'Helvetica' }
      };
    }

    // Note: Trong môi trường thực tế cần setup Font path
    const fonts = {
      Helvetica: {
        normal: 'Helvetica',
        bold: 'Helvetica-Bold',
        italics: 'Helvetica-Oblique',
        bolditalics: 'Helvetica-BoldOblique'
      },
      Courier: {
        normal: 'Courier',
        bold: 'Courier-Bold'
      }
    };

    try {
      const printer = new PdfPrinter(fonts);
      const pdfDoc = printer.createPdfKitDocument(docDefinition);
      
      const uploadDir = path.join(process.cwd(), 'uploads', 'documents');
      if (!fs.existsSync(uploadDir)) fs.mkdirSync(uploadDir, { recursive: true });
      
      const filePath = path.join(uploadDir, doc.fileName);
      pdfDoc.pipe(fs.createWriteStream(filePath));
      pdfDoc.end();

      // Update DB
      doc.isGenerated = true;
      doc.fileUrl = `/uploads/documents/${doc.fileName}`;
      await this.docsRepository.save(doc);
      
      console.log(`PDF Generated successfully: ${filePath}`);
    } catch (error) {
      console.error('Error generating PDF:', error);
    }
  }

  private getCommercialInvoiceDefinition(doc: ExportDocument) {
    const data = doc.snapshotData || {};
    const items = data.items || [];

    return {
      content: [
        { text: 'COMMERCIAL INVOICE', style: 'header', alignment: 'center' },
        { text: `No: ${data.invoiceNumber || 'N/A'}`, alignment: 'right' },
        { text: `Date: ${new Date().toLocaleDateString()}`, alignment: 'right', margin: [0, 0, 0, 20] },

        {
          columns: [
            {
              width: '*',
              stack: [
                { text: 'SELLER:', bold: true },
                { text: 'MINI ERP EXPORT TRADING CO.' },
                { text: 'Ho Chi Minh City, Vietnam' },
              ]
            },
            {
              width: '*',
              stack: [
                { text: 'BUYER:', bold: true },
                { text: data.buyerName || 'N/A' },
                { text: data.buyerAddress || 'N/A' },
              ]
            }
          ],
          margin: [0, 0, 0, 20]
        },

        {
          table: {
            headerRows: 1,
            widths: ['*', 'auto', 'auto', 'auto'],
            body: [
              [
                { text: 'Description', bold: true },
                { text: 'Qty', bold: true },
                { text: 'Unit Price', bold: true },
                { text: 'Amount', bold: true }
              ],
              ...items.map((item: any) => [
                item.productName || item.sku,
                item.quantity,
                `${item.unitPrice} ${data.currency || 'USD'}`,
                `${item.totalPrice} ${data.currency || 'USD'}`
              ]),
              [
                { text: 'TOTAL', bold: true, colSpan: 3 },
                {},
                {},
                { text: `${data.totalAmount} ${data.currency || 'USD'}`, bold: true }
              ]
            ]
          }
        },

        { text: `Incoterm: ${data.incoterm || 'FOB'}`, margin: [0, 20, 0, 0] },
        { text: `Payment Terms: ${data.paymentTerms || 'T/T'}`, margin: [0, 5, 0, 0] },
        { text: '\n\nAuthorized Signature', alignment: 'right', margin: [0, 50, 0, 0] }
      ],
      styles: {
        header: { fontSize: 24, bold: true, margin: [0, 0, 0, 10] },
        footer: { fontSize: 10, italic: true, alignment: 'center' }
      },
      defaultStyle: { font: 'Helvetica' }
    };
  }

  private getPackingListDefinition(doc: ExportDocument) {
    const data = doc.snapshotData || {};
    const items = data.items || [];

    return {
      content: [
        { text: 'PACKING LIST', style: 'header', alignment: 'center' },
        { text: `No: ${data.invoiceNumber || 'N/A'}`, alignment: 'right' },
        { text: `Date: ${new Date().toLocaleDateString()}`, alignment: 'right', margin: [0, 0, 0, 20] },

        {
          table: {
            headerRows: 1,
            widths: ['*', 'auto', 'auto', 'auto', 'auto'],
            body: [
              [
                { text: 'Description', bold: true },
                { text: 'Qty', bold: true },
                { text: 'N.W (KGS)', bold: true },
                { text: 'G.W (KGS)', bold: true },
                { text: 'CBM', bold: true }
              ],
              ...items.map((item: any) => [
                item.productName || item.sku,
                item.quantity,
                item.netWeight || '-',
                item.grossWeight || '-',
                item.cbm || '-'
              ])
            ]
          }
        },

        { text: '\n\nAuthorized Signature', alignment: 'right', margin: [0, 50, 0, 0] }
      ],
      styles: {
        header: { fontSize: 24, bold: true, margin: [0, 0, 0, 10] },
      },
      defaultStyle: { font: 'Helvetica' }
    };
  }
}
